export const categories = [
  { name: "Fresh Produce", icon: "leaf" as const, color: "bg-emerald-100 text-emerald-700" },
  { name: "Meat & Seafood", icon: "fish" as const, color: "bg-red-100 text-red-600" },
  { name: "Dairy & Eggs", icon: "egg" as const, color: "bg-yellow-100 text-yellow-700" },
  { name: "Beverages", icon: "coffee" as const, color: "bg-amber-100 text-amber-700" },
  { name: "Dry Goods", icon: "wheat" as const, color: "bg-orange-100 text-orange-700" },
  { name: "Condiments", icon: "flask" as const, color: "bg-rose-100 text-rose-600" },
  { name: "Frozen Foods", icon: "snowflake" as const, color: "bg-sky-100 text-sky-600" },
  { name: "Packaging", icon: "package" as const, color: "bg-gray-100 text-gray-600" },
];

export const services = [
  { label: "Fast & Easy Delivery", icon: "truck" as const },
  { label: "Verified Suppliers", icon: "shield-check" as const },
  { label: "Best Prices", icon: "tag" as const },
  { label: "24/7 Support", icon: "headphones" as const },
  { label: "Secure Payments", icon: "credit-card" as const },
];

export type ProductCategory = "all" | "veggies" | "fruits" | "meat" | "seafood";

export const products = [
  {
    id: 1,
    name: "Organic Cherry Tomatoes",
    supplier: "Green Farm Cambodia",
    location: "Kandal",
    price: 2.5,
    badge: "Organic",
    badgeColor: "bg-emerald-600",
    category: "veggies" as const,
    gradient: "from-red-400 to-red-600",
  },
  {
    id: 2,
    name: "Wild-Caught Tiger Prawns",
    supplier: "Mekong Fresh Co.",
    location: "Kampot",
    price: 11.8,
    badge: "New",
    badgeColor: "bg-blue-600",
    category: "seafood" as const,
    gradient: "from-orange-300 to-orange-500",
  },
  {
    id: 3,
    name: "Kampot Kampong Chhnang Rice",
    supplier: "Rice Valley Co-op",
    location: "Kampong Chhnang",
    price: 3.2,
    badge: null,
    badgeColor: "",
    category: "veggies" as const,
    gradient: "from-amber-200 to-amber-400",
  },
  {
    id: 4,
    name: "Single-Origin Robusta Beans",
    supplier: "Highland Coffee Co.",
    location: "Mondulkiri",
    price: 8.5,
    badge: "Sale",
    badgeColor: "bg-red-500",
    category: "fruits" as const,
    gradient: "from-amber-700 to-amber-900",
  },
  {
    id: 5,
    name: "Free Range Eggs (12 pack)",
    supplier: "Happy Hens Farm",
    location: "Takeo",
    price: 4.0,
    badge: null,
    badgeColor: "",
    category: "meat" as const,
    gradient: "from-yellow-200 to-yellow-400",
  },
  {
    id: 6,
    name: "Pad Thai Noodle Set",
    supplier: "Asian Pantry Co.",
    location: "Phnom Penh",
    price: 5.5,
    badge: "New",
    badgeColor: "bg-blue-600",
    category: "veggies" as const,
    gradient: "from-orange-200 to-orange-400",
  },
  {
    id: 7,
    name: "Fresh Baby Spinach",
    supplier: "Green Farm Cambodia",
    location: "Kandal",
    price: 1.8,
    badge: "Organic",
    badgeColor: "bg-emerald-600",
    category: "veggies" as const,
    gradient: "from-green-400 to-green-600",
  },
  {
    id: 8,
    name: "Fish Sauce Premium",
    supplier: "Coastal Condiments",
    location: "Kampot",
    price: 3.9,
    badge: null,
    badgeColor: "",
    category: "seafood" as const,
    gradient: "from-amber-600 to-amber-800",
  },
];

export const suppliers = [
  {
    name: "Green Farm Cambodia",
    type: "Local Farm",
    location: "Kandal Province",
    rating: 4.8,
    initials: "GF",
    color: "bg-emerald-600",
  },
  {
    name: "Mekong Fresh Co.",
    type: "Seafood Supplier",
    location: "Kampot Province",
    rating: 4.9,
    initials: "MF",
    color: "bg-blue-600",
  },
  {
    name: "Highland Coffee Co.",
    type: "Beverage Supplier",
    location: "Mondulkiri",
    rating: 4.7,
    initials: "HC",
    color: "bg-amber-700",
  },
  {
    name: "Rice Valley Co-op",
    type: "Grain Supplier",
    location: "Kampong Chhnang",
    rating: 4.6,
    initials: "RV",
    color: "bg-orange-600",
  },
];

export const productTabs: { id: ProductCategory; label: string }[] = [
  { id: "all", label: "All" },
  { id: "veggies", label: "Veggies" },
  { id: "fruits", label: "Fruits" },
  { id: "meat", label: "Meat" },
  { id: "seafood", label: "Seafood" },
];
